#include <KEngine/Input/Keyboard/SFMLKeyboard.hpp>
#include <KEngine/Dev/dbg.hpp>

namespace ke
{

bool SFMLKeyboard::keyPressed(const ke::Key p_Key)
{
    return sf::Keyboard::isKeyPressed(ke::SFMLKey_Cast(p_Key));
}

bool SFMLKeyboard::keyReleased(const ke::Key p_Key)
{
    return !sf::Keyboard::isKeyPressed(ke::SFMLKey_Cast(p_Key));
}

sf::Keyboard::Key SFMLKey_Cast(const ke::Key p_Key)
{
    switch (p_Key)
    {
    case ke::Key::A:
        return sf::Keyboard::Key::A;
    case ke::Key::B:
        return sf::Keyboard::Key::B;
    case ke::Key::C:
        return sf::Keyboard::Key::C;
    case ke::Key::D:
        return sf::Keyboard::Key::D;
    case ke::Key::E:
        return sf::Keyboard::Key::E;
    case ke::Key::F:
        return sf::Keyboard::Key::F;
    case ke::Key::G:
        return sf::Keyboard::Key::G;
    case ke::Key::H:
        return sf::Keyboard::Key::H;
    case ke::Key::I:
        return sf::Keyboard::Key::I;
    case ke::Key::J:
        return sf::Keyboard::Key::J;
    case ke::Key::K:
        return sf::Keyboard::Key::K;
    case ke::Key::L:
        return sf::Keyboard::Key::L;
    case ke::Key::M:
        return sf::Keyboard::Key::M;
    case ke::Key::N:
        return sf::Keyboard::Key::N;
    case ke::Key::O:
        return sf::Keyboard::Key::O;
    case ke::Key::P:
        return sf::Keyboard::Key::P;
    case ke::Key::Q:
        return sf::Keyboard::Key::Q;
    case ke::Key::R:
        return sf::Keyboard::Key::R;
    case ke::Key::S:
        return sf::Keyboard::Key::S;
    case ke::Key::T:
        return sf::Keyboard::Key::T;
    case ke::Key::U:
        return sf::Keyboard::Key::U;
    case ke::Key::V:
        return sf::Keyboard::Key::V;
    case ke::Key::W:
        return sf::Keyboard::Key::W;
    case ke::Key::X:
        return sf::Keyboard::Key::X;
    case ke::Key::Y:
        return sf::Keyboard::Key::Y;
    case ke::Key::Z:
        return sf::Keyboard::Key::Z;
    case ke::Key::Num1:
        return sf::Keyboard::Key::Num1;
    case ke::Key::Num2:
        return sf::Keyboard::Key::Num2;
    case ke::Key::Num3:
        return sf::Keyboard::Key::Num3;
    case ke::Key::Num4:
        return sf::Keyboard::Key::Num4;
    case ke::Key::Num5:
        return sf::Keyboard::Key::Num5;
    case ke::Key::Num6:
        return sf::Keyboard::Key::Num6;
    case ke::Key::Num7:
        return sf::Keyboard::Key::Num7;
    case ke::Key::Num8:
        return sf::Keyboard::Key::Num8;
    case ke::Key::Num9:
        return sf::Keyboard::Key::Num9;
    case ke::Key::Num0:
        return sf::Keyboard::Key::Num0;
    case ke::Key::Numpad1:
        return sf::Keyboard::Key::Numpad1;
    case ke::Key::Numpad2:
        return sf::Keyboard::Key::Numpad2;
    case ke::Key::Numpad3:
        return sf::Keyboard::Key::Numpad3;
    case ke::Key::Numpad4:
        return sf::Keyboard::Key::Numpad4;
    case ke::Key::Numpad5:
        return sf::Keyboard::Key::Numpad5;
    case ke::Key::Numpad6:
        return sf::Keyboard::Key::Numpad6;
    case ke::Key::Numpad7:
        return sf::Keyboard::Key::Numpad7;
    case ke::Key::Numpad8:
        return sf::Keyboard::Key::Numpad8;
    case ke::Key::Numpad9:
        return sf::Keyboard::Key::Numpad9;
    case ke::Key::Numpad0:
        return sf::Keyboard::Key::Numpad0;
    case ke::Key::F1:
        return sf::Keyboard::Key::F1;
    case ke::Key::F2:
        return sf::Keyboard::Key::F2;
    case ke::Key::F3:
        return sf::Keyboard::Key::F3;
    case ke::Key::F4:
        return sf::Keyboard::Key::F4;
    case ke::Key::F5:
        return sf::Keyboard::Key::F5;
    case ke::Key::F6:
        return sf::Keyboard::Key::F6;
    case ke::Key::F7:
        return sf::Keyboard::Key::F7;
    case ke::Key::F8:
        return sf::Keyboard::Key::F8;
    case ke::Key::F9:
        return sf::Keyboard::Key::F9;
    case ke::Key::F10:
        return sf::Keyboard::Key::F10;
    case ke::Key::F11:
        return sf::Keyboard::Key::F11;
    case ke::Key::F12:
        return sf::Keyboard::Key::F12;
    case ke::Key::F13:
        return sf::Keyboard::Key::F13;
    case ke::Key::F14:
        return sf::Keyboard::Key::F14;
    case ke::Key::F15:
        return sf::Keyboard::Key::F15;
    case ke::Key::Escape:
        return sf::Keyboard::Key::Escape;
    case ke::Key::LControl:
        return sf::Keyboard::Key::LControl;
    case ke::Key::LShift:
        return sf::Keyboard::Key::LShift;
    case ke::Key::LAlt:
        return sf::Keyboard::Key::LAlt;
    case ke::Key::LSystem:
        return sf::Keyboard::Key::LSystem;
    case ke::Key::RControl:
        return sf::Keyboard::Key::RControl;
    case ke::Key::RShift:
        return sf::Keyboard::Key::RShift;
    case ke::Key::RAlt:
        return sf::Keyboard::Key::RAlt;
    case ke::Key::RSystem:
        return sf::Keyboard::Key::RSystem;
    case ke::Key::Menu:
        return sf::Keyboard::Key::Menu;
    case ke::Key::LBracket:
        return sf::Keyboard::Key::LBracket;
    case ke::Key::RBracket:
        return sf::Keyboard::Key::RBracket;
    case ke::Key::SemiColon:
        return sf::Keyboard::Key::SemiColon;
    case ke::Key::Comma:
        return sf::Keyboard::Key::Comma;
    case ke::Key::Period:
        return sf::Keyboard::Key::Period;
    case ke::Key::Quote:
        return sf::Keyboard::Key::Quote;
    case ke::Key::Slash:
        return sf::Keyboard::Key::Slash;
    case ke::Key::BackSlash:
        return sf::Keyboard::Key::BackSlash;
    case ke::Key::Tilde:
        return sf::Keyboard::Key::Tilde;
    case ke::Key::Equal:
        return sf::Keyboard::Key::Equal;
    case ke::Key::Dash:
        return sf::Keyboard::Key::Dash;
    case ke::Key::Space:
        return sf::Keyboard::Key::Space;
    case ke::Key::Return:
        return sf::Keyboard::Key::Return;
    case ke::Key::BackSpace:
        return sf::Keyboard::Key::BackSpace;
    case ke::Key::Tab:
        return sf::Keyboard::Key::Tab;
    case ke::Key::PageUp:
        return sf::Keyboard::Key::PageUp;
    case ke::Key::PageDown:
        return sf::Keyboard::Key::PageDown;
    case ke::Key::End:
        return sf::Keyboard::Key::End;
    case ke::Key::Home:
        return sf::Keyboard::Key::Home;
    case ke::Key::Insert:
        return sf::Keyboard::Key::Insert;
    case ke::Key::Delete:
        return sf::Keyboard::Key::Delete;
    case ke::Key::Add:
        return sf::Keyboard::Key::Add;
    case ke::Key::Subtract:
        return sf::Keyboard::Key::Subtract;
    case ke::Key::Multiply:
        return sf::Keyboard::Key::Multiply;
    case ke::Key::Divide:
        return sf::Keyboard::Key::Divide;
    case ke::Key::Left:
        return sf::Keyboard::Key::Left;
    case ke::Key::Right:
        return sf::Keyboard::Key::Right;
    case ke::Key::Up:
        return sf::Keyboard::Key::Up;
    case ke::Key::Down:
        return sf::Keyboard::Key::Down;

    case ke::Key::Invalid:
    case ke::Key::Unknown:
    case ke::Key::F16:
    case ke::Key::F17:
    case ke::Key::F18:
    case ke::Key::F19:
    case ke::Key::F20:
    case ke::Key::F21:
    case ke::Key::F22:
    case ke::Key::F23:
    case ke::Key::F24:
    case ke::Key::F25:
    case ke::Key::F26:
    case ke::Key::F27:
    case ke::Key::F28:
    case ke::Key::F29:
    case ke::Key::F30:
    case ke::Key::NumKey:
    default:
    {
        ke::Debug::printWarning("ke::SFMLKey_Cast : This implementation does not support this key.");
        return sf::Keyboard::Key::Unknown;
    }
    }
}

ke::Key KEKey_Cast(const sf::Keyboard::Key p_Key)
{
    switch (p_Key)
    {
    case sf::Keyboard::Key::A:
        return ke::Key::A;
    case sf::Keyboard::Key::B:
        return ke::Key::B;
    case sf::Keyboard::Key::C:
        return ke::Key::C;
    case sf::Keyboard::Key::D:
        return ke::Key::D;
    case sf::Keyboard::Key::E:
        return ke::Key::E;
    case sf::Keyboard::Key::F:
        return ke::Key::F;
    case sf::Keyboard::Key::G:
        return ke::Key::G;
    case sf::Keyboard::Key::H:
        return ke::Key::H;
    case sf::Keyboard::Key::I:
        return ke::Key::I;
    case sf::Keyboard::Key::J:
        return ke::Key::J;
    case sf::Keyboard::Key::K:
        return ke::Key::K;
    case sf::Keyboard::Key::L:
        return ke::Key::L;
    case sf::Keyboard::Key::M:
        return ke::Key::M;
    case sf::Keyboard::Key::N:
        return ke::Key::N;
    case sf::Keyboard::Key::O:
        return ke::Key::O;
    case sf::Keyboard::Key::P:
        return ke::Key::P;
    case sf::Keyboard::Key::Q:
        return ke::Key::Q;
    case sf::Keyboard::Key::R:
        return ke::Key::R;
    case sf::Keyboard::Key::S:
        return ke::Key::S;
    case sf::Keyboard::Key::T:
        return ke::Key::T;
    case sf::Keyboard::Key::U:
        return ke::Key::U;
    case sf::Keyboard::Key::V:
        return ke::Key::V;
    case sf::Keyboard::Key::W:
        return ke::Key::W;
    case sf::Keyboard::Key::X:
        return ke::Key::X;
    case sf::Keyboard::Key::Y:
        return ke::Key::Y;
    case sf::Keyboard::Key::Z:
        return ke::Key::Z;
    case sf::Keyboard::Key::Num1:
        return ke::Key::Num1;
    case sf::Keyboard::Key::Num2:
        return ke::Key::Num2;
    case sf::Keyboard::Key::Num3:
        return ke::Key::Num3;
    case sf::Keyboard::Key::Num4:
        return ke::Key::Num4;
    case sf::Keyboard::Key::Num5:
        return ke::Key::Num5;
    case sf::Keyboard::Key::Num6:
        return ke::Key::Num6;
    case sf::Keyboard::Key::Num7:
        return ke::Key::Num7;
    case sf::Keyboard::Key::Num8:
        return ke::Key::Num8;
    case sf::Keyboard::Key::Num9:
        return ke::Key::Num9;
    case sf::Keyboard::Key::Num0:
        return ke::Key::Num0;
    case sf::Keyboard::Key::Numpad1:
        return ke::Key::Numpad1;
    case sf::Keyboard::Key::Numpad2:
        return ke::Key::Numpad2;
    case sf::Keyboard::Key::Numpad3:
        return ke::Key::Numpad3;
    case sf::Keyboard::Key::Numpad4:
        return ke::Key::Numpad4;
    case sf::Keyboard::Key::Numpad5:
        return ke::Key::Numpad5;
    case sf::Keyboard::Key::Numpad6:
        return ke::Key::Numpad6;
    case sf::Keyboard::Key::Numpad7:
        return ke::Key::Numpad7;
    case sf::Keyboard::Key::Numpad8:
        return ke::Key::Numpad8;
    case sf::Keyboard::Key::Numpad9:
        return ke::Key::Numpad9;
    case sf::Keyboard::Key::Numpad0:
        return ke::Key::Numpad0;
    case sf::Keyboard::Key::F1:
        return ke::Key::F1;
    case sf::Keyboard::Key::F2:
        return ke::Key::F2;
    case sf::Keyboard::Key::F3:
        return ke::Key::F3;
    case sf::Keyboard::Key::F4:
        return ke::Key::F4;
    case sf::Keyboard::Key::F5:
        return ke::Key::F5;
    case sf::Keyboard::Key::F6:
        return ke::Key::F6;
    case sf::Keyboard::Key::F7:
        return ke::Key::F7;
    case sf::Keyboard::Key::F8:
        return ke::Key::F8;
    case sf::Keyboard::Key::F9:
        return ke::Key::F9;
    case sf::Keyboard::Key::F10:
        return ke::Key::F10;
    case sf::Keyboard::Key::F11:
        return ke::Key::F11;
    case sf::Keyboard::Key::F12:
        return ke::Key::F12;
    case sf::Keyboard::Key::F13:
        return ke::Key::F13;
    case sf::Keyboard::Key::F14:
        return ke::Key::F14;
    case sf::Keyboard::Key::F15:
        return ke::Key::F15;
    case sf::Keyboard::Key::Escape:
        return ke::Key::Escape;
    case sf::Keyboard::Key::LControl:
        return ke::Key::LControl;
    case sf::Keyboard::Key::LShift:
        return ke::Key::LShift;
    case sf::Keyboard::Key::LAlt:
        return ke::Key::LAlt;
    case sf::Keyboard::Key::LSystem:
        return ke::Key::LSystem;
    case sf::Keyboard::Key::RControl:
        return ke::Key::RControl;
    case sf::Keyboard::Key::RShift:
        return ke::Key::RShift;
    case sf::Keyboard::Key::RAlt:
        return ke::Key::RAlt;
    case sf::Keyboard::Key::RSystem:
        return ke::Key::RSystem;
    case sf::Keyboard::Key::Menu:
        return ke::Key::Menu;
    case sf::Keyboard::Key::LBracket:
        return ke::Key::LBracket;
    case sf::Keyboard::Key::RBracket:
        return ke::Key::RBracket;
    case sf::Keyboard::Key::SemiColon:
        return ke::Key::SemiColon;
    case sf::Keyboard::Key::Comma:
        return ke::Key::Comma;
    case sf::Keyboard::Key::Period:
        return ke::Key::Period;
    case sf::Keyboard::Key::Quote:
        return ke::Key::Quote;
    case sf::Keyboard::Key::Slash:
        return ke::Key::Slash;
    case sf::Keyboard::Key::BackSlash:
        return ke::Key::BackSlash;
    case sf::Keyboard::Key::Tilde:
        return ke::Key::Tilde;
    case sf::Keyboard::Key::Equal:
        return ke::Key::Equal;
    case sf::Keyboard::Key::Dash:
        return ke::Key::Dash;
    case sf::Keyboard::Key::Space:
        return ke::Key::Space;
    case sf::Keyboard::Key::Return:
        return ke::Key::Return;
    case sf::Keyboard::Key::BackSpace:
        return ke::Key::BackSpace;
    case sf::Keyboard::Key::Tab:
        return ke::Key::Tab;
    case sf::Keyboard::Key::PageUp:
        return ke::Key::PageUp;
    case sf::Keyboard::Key::PageDown:
        return ke::Key::PageDown;
    case sf::Keyboard::Key::End:
        return ke::Key::End;
    case sf::Keyboard::Key::Home:
        return ke::Key::Home;
    case sf::Keyboard::Key::Insert:
        return ke::Key::Insert;
    case sf::Keyboard::Key::Delete:
        return ke::Key::Delete;
    case sf::Keyboard::Key::Add:
        return ke::Key::Add;
    case sf::Keyboard::Key::Subtract:
        return ke::Key::Subtract;
    case sf::Keyboard::Key::Multiply:
        return ke::Key::Multiply;
    case sf::Keyboard::Key::Divide:
        return ke::Key::Divide;
    case sf::Keyboard::Key::Left:
        return ke::Key::Left;
    case sf::Keyboard::Key::Right:
        return ke::Key::Right;
    case sf::Keyboard::Key::Up:
        return ke::Key::Up;
    case sf::Keyboard::Key::Down:
        return ke::Key::Down;
    case sf::Keyboard::Key::Unknown:
        return ke::Key::Unknown;

    default:
    {
        ke::Debug::printWarning("ke::KEKey_Cast  : This implementation does not support this key.");
        return ke::Key::Unknown;
    }
    }
}

} // KE ns